#!/bin/sh

fail () {
   cat <<EOF
ERROR: $1
Usage: $0 <options>
  -h for more details
EOF
exit 1
}

usage()
{
cat <<EOF
Usage: $0 [options]
where [options] include:

  -h print this message and exit

  -c <configuration> the configuration that longwell should start
     default: longwell

  -p <path> is the paths where longwell will look for configurations
     default:  ./src/main/webapp/

  -d <database> the directory were the triple store files reside
     default:  ./src/main/webapp/WEB-INF/database

  -a <action> is what to do, the default is run
   supported <action>s are:
    run          Run longwell
    debug        Run longwell and turn on JVM remote debug
    profile      Run longwell and turn on JVM profiling with HProf
    shark        Run longwell and turn on JVM profiling with Apple Shark (MacOSX only)
    yourkit      Run longwell and turn on JVM profiling with YourKit
    jmx          Run longwell and turn on JVM monitoring with JMX and JConsole

  -r <rdf> is the directory where the RDF data to load is
    default: no data is loaded
EOF
    exit 0
}

### Parse the command line args.

ACTION='run'
MAVEN_OPTS='-Djava.awt.headless=true'

add_option () {
  MAVEN_OPTS="$MAVEN_OPTS $1"
}

absolute_path () {
  case $1 in
    /*) echo $1; ;;
    *) echo `pwd`/$1; ;;
  esac
}

while [ $# -ne 0 ] ; do
  case "x$1" in
    x-c) shift; add_option "-Dlongwell.configuration=$1"; shift; ;;
    x-d) shift; add_option "-Dlongwell.store.dir=$1"; shift; ;;
    x-p) shift; add_option "-Dlongwell.configuration.path=`absolute_path $1`"; shift; ;;
    x-r) shift; add_option "-Dlongwell.data=`absolute_path $1`"; shift; ;;
    x-a) shift; ACTION="$1"; shift; ;;
    x-h) usage; ;;
    *) fail "malformed argument '$1', '$*' remain"; ;;
  esac
done

# ----- Verify and Set Required Environment Variables -------------------------

if [ "$JETTY_PORT" = "" ] ; then
  JETTY_PORT=8080
fi
add_option "-Djetty.port=$JETTY_PORT"

if [ "$JAVA_OPTIONS" = "" ] ; then
  JAVA_OPTIONS="-Xms32M -Xmx128M"
fi
add_option "$JAVA_OPTIONS"

# ----- Respond to the action given. ----------------------------------------------------------

case "$ACTION" in
  run) ;;
  debug)
    add_option '-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n'; ;;
  profile)
    add_option '-Xrunhprof:heap=all,cpu=samples,thread=y,depth=3'; ;;
  shark)
    add_option '-Xrunshark'; ;;
  yourkit)
    add_option '-agentlib:yjpagent'; ;;
  jmx)
    add_option '-Dcom.sun.management.jmxremote'; ;;
  *)
    fail "Unknown action '$ACTION'"; ;;
esac

export MAVEN_OPTS
echo "[INFO] MAVEN_OPTS: '$MAVEN_OPTS'"
exec mvn $MAVEN_PARAMS jetty:run
