#!/bin/tcsh -f
# get the correct working directory
set mypath=$0
if ($mypath == "bib2rdf") set mypath=`which bib2rdf`
set mypath=$mypath:h
java -classpath ${mypath}/libraries/fulljena.jar:${mypath}/source edu.mit.csail.haystack.rdf.converters.BibtexParser $*

