/* Generated By:JavaCC: Do not edit this line. BibtexGrammarConstants.java */
package edu.mit.simile.babel.bibtex.internal;

public interface BibtexGrammarConstants {

  int EOF = 0;
  int AT = 1;
  int WS = 2;
  int STR = 3;
  int PRE = 4;
  int EQ = 5;
  int HASH = 6;
  int COMMA = 7;
  int LPAREN = 8;
  int RPAREN = 9;
  int QUOTE = 10;
  int LBRACE = 11;
  int RBRACE = 12;
  int DELIM = 13;
  int QCHAR = 14;
  int WORD = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"@\"",
    "<WS>",
    "\"string\"",
    "\"preamble\"",
    "\"=\"",
    "\"#\"",
    "<COMMA>",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "<DELIM>",
    "<QCHAR>",
    "<WORD>",
  };

}
