/* Generated By:JavaCC: Do not edit this line. BibtexGrammar.java */
package edu.mit.simile.babel.bibtex.internal;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import edu.mit.simile.babel.bibtex.BibMap;

// Can't deal with quoted percent \%

public final class BibtexGrammar implements BibtexGrammarConstants {

        static final String [][] months = new String[][]{
                {"jan", "{January}"}, {"feb", "{February}"},
                {"mar", "{March}"}, {"apr", "{April}"},
                {"may", "{May}"}, {"jun", "{June}"},
                {"jul", "{July}"}, {"aug", "{August}"},
                {"sep", "{September}"}, {"oct", "{October}"},
                {"nov", "{November}"}, {"dec", "{December}"}};

        private String preamble = "";
        private Map strings = new HashMap();
        private List records = new ArrayList();

        /** Returns the records.  Should be called after parse(). */
        public List getRecords(){
                return records;
        }

        /** Parses a file and prints debugging output. */
        public static void main(String args[]) throws ParseException{
                try{
                        BibtexGrammar p =
                                new BibtexGrammar(new BufferedReader(new FileReader(args[0])));
                        p.parse();
                        p.printout();
                }
                catch(FileNotFoundException e){e.printStackTrace();}
        }

        /** Prints debugging output. Should be called after parse(). */
        void printout(){
                if(!"".equals(preamble))
                        System.out.println("DEBUG: Found Preamble: \n" + preamble);
                System.out.println("DEBUG: Found " + strings.size() + " Strings:");
                Iterator iter = strings.keySet().iterator();
                while(iter.hasNext()){
                        Object key = iter.next();
                        System.out.println("\t" + key + "\t" + strings.get(key));
                }
                System.out.println("DEBUG: Found " + records.size() + " Records:");
                iter = records.iterator();
                while(iter.hasNext()){
                        System.out.println("\n ----------------------------------- ");
                        BibMap record = (BibMap) iter.next();
                        System.out.println("TYPE:\t" + record.getType());
                        System.out.println("KEY:\t" + record.getKey());
                        Iterator jiter = record.keySet().iterator();
                        while(jiter.hasNext()){
                                String key = (String) jiter.next();
                                System.out.println("\tFIELD:\t" + key
                                                                   + "\t" + record.get(key));
                        }
                }
        }

/*
SPECIAL_TOKEN:{
	<COMMENT: "%" (~["\n", "\r"])* <WS> | "">
}
*/

/** A bibtex file is basically a concatenation of records, which are
	either string definitions or proper bibliographic records.  This
	method just consumes records until the file ends, at which point it
	resolves cross-references within individual records. */
  final public void parse() throws ParseException {
        // Load the default string expansions for months.  My impression
        // is that these are supposed to expand to locale-specific strings
        // for the month.  This hack effectively makes this an "English 
        // bibtex parser"
        for(int i=0; i<months.length; i++)
                strings.put(months[i][0], months[i][1]);
    label_1:
    while (true) {
      if (jj_2_1(3)) {
        ;
      } else {
        break label_1;
      }
      if (jj_2_2(3)) {
        strdef();
      } else if (jj_2_3(3)) {
        recdef();
      } else if (jj_2_4(3)) {
        predef();
      } else if (jj_2_5(3)) {
        jj_consume_token(WS);
      } else if (jj_2_6(3)) {
        jj_consume_token(0);
                                               {if (true) return;}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/** Consumes a preamble definition. */
  final public void predef() throws ParseException {
               String val;
    jj_consume_token(AT);
    jj_consume_token(PRE);
    if (jj_2_7(3)) {
      jj_consume_token(WS);
    } else {
      ;
    }
    if (jj_2_12(3)) {
      jj_consume_token(LBRACE);
      if (jj_2_8(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      val = vals();
      if (jj_2_9(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(RBRACE);
    } else if (jj_2_13(3)) {
      jj_consume_token(LPAREN);
      if (jj_2_10(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      val = vals();
      if (jj_2_11(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(RPAREN);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                  preamble = preamble + val;
  }

/** Consumes a single string definition. A string definition is
	basically a single pair. */
  final public void strdef() throws ParseException {
    jj_consume_token(AT);
    jj_consume_token(STR);
    if (jj_2_14(3)) {
      jj_consume_token(WS);
    } else {
      ;
    }
    if (jj_2_17(3)) {
      jj_consume_token(LBRACE);
      pair(strings);
      if (jj_2_15(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(RBRACE);
    } else if (jj_2_18(3)) {
      jj_consume_token(LPAREN);
      pair(strings);
      if (jj_2_16(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(RPAREN);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/** Consumes a single record definition. */
  final public void recdef() throws ParseException {
        Token t1, t2=null;
        BibMap record = new BibMap();
    jj_consume_token(AT);
    t1 = jj_consume_token(WORD);
    if (jj_2_19(3)) {
      jj_consume_token(WS);
    } else {
      ;
    }
    if (jj_2_28(3)) {
      jj_consume_token(LBRACE);
      if (jj_2_20(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      t2 = jj_consume_token(WORD);
      label_2:
      while (true) {
        if (jj_2_21(3)) {
          ;
        } else {
          break label_2;
        }
        jj_consume_token(COMMA);
        pair(record);
      }
      if (jj_2_22(3)) {
        jj_consume_token(COMMA);
      } else {
        ;
      }
      if (jj_2_23(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(RBRACE);
    } else if (jj_2_29(3)) {
      jj_consume_token(LPAREN);
      if (jj_2_24(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      t2 = jj_consume_token(WORD);
      label_3:
      while (true) {
        if (jj_2_25(3)) {
          ;
        } else {
          break label_3;
        }
        jj_consume_token(COMMA);
        pair(record);
      }
      if (jj_2_26(3)) {
        jj_consume_token(COMMA);
      } else {
        ;
      }
      if (jj_2_27(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(RPAREN);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
          String type = t1.toString().toLowerCase(), key=t2.toString();
          record.setType(type.equals("conference") ? "inproceedings" : type);
          record.setKey(key);
          records.add(record);
  }

/** Consumes a pair and places them in map. */
  final public void pair(Map map) throws ParseException {
        Token id;
        String val;
    if (jj_2_30(3)) {
      jj_consume_token(WS);
    } else {
      ;
    }
    id = jj_consume_token(WORD);
    if (jj_2_31(3)) {
      jj_consume_token(WS);
    } else {
      ;
    }
    jj_consume_token(EQ);
    if (jj_2_32(3)) {
      jj_consume_token(WS);
    } else {
      ;
    }
    val = vals();
         map.put(id.toString().toLowerCase(), val);
  }

/** Consumes a concatenation of "values" */
  final public String vals() throws ParseException {
        String val;
        StringBuffer sb = new StringBuffer();
    val = val();
                     sb.append(val);
    label_4:
    while (true) {
      if (jj_2_33(3)) {
        ;
      } else {
        break label_4;
      }
      if (jj_2_34(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      jj_consume_token(HASH);
      if (jj_2_35(3)) {
        jj_consume_token(WS);
      } else {
        ;
      }
      val = val();
                        if(sb.charAt(0) == '{')
                            sb.deleteCharAt(sb.length()-1); // must be a curly brace
                        if(val.startsWith("{"))
                        val = val.substring(1, val.length()-1);
                  sb.append(val + "}");
                        //		  sb.append(" " + val + "}");

    }
   {if (true) return sb.toString();}
    throw new Error("Missing return statement in function");
  }

/** Consumes a value, plus any trailing whitespace */
  final public String val() throws ParseException {
        Token token;
        String val;
    if (jj_2_36(3)) {
      jj_consume_token(LBRACE);
      val = wordsq();
      jj_consume_token(RBRACE);
                                    {if (true) return "{" + val + "}";}
    } else if (jj_2_37(3)) {
      jj_consume_token(QUOTE);
      val = words();
      jj_consume_token(QUOTE);
                                   {if (true) return "{" + val + "}";}
    } else if (jj_2_38(3)) {
      token = jj_consume_token(WORD);
        String key = token.toString().toLowerCase();
        if (strings.containsKey(key))
                {if (true) return (String) strings.get(key);}
        else
                {if (true) return key;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/** Consumes a set of words, where a quote token is a word. */
  final public String wordsq() throws ParseException {
        String s;
        Token t;
        StringBuffer sb = new StringBuffer();
    label_5:
    while (true) {
      if (jj_2_39(3)) {
        ;
      } else {
        break label_5;
      }
      if (jj_2_40(3)) {
        s = wordq();
                    sb.append(s);
      } else if (jj_2_41(3)) {
        jj_consume_token(LBRACE);
        s = wordsq();
        jj_consume_token(RBRACE);
                                        sb.append("{" + s + "}");
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
 {if (true) return sb.toString();}
    throw new Error("Missing return statement in function");
  }

/** Consumes a set of words, where a quote token is not a word. */
  final public String words() throws ParseException {
        String s;
        Token t;
        StringBuffer sb = new StringBuffer();
    label_6:
    while (true) {
      if (jj_2_42(3)) {
        ;
      } else {
        break label_6;
      }
      if (jj_2_43(3)) {
        s = word();
                   sb.append(s);
      } else if (jj_2_44(3)) {
        jj_consume_token(LBRACE);
        s = wordsq();
        jj_consume_token(RBRACE);
                                        sb.append("{" + s + "}");
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
 {if (true) return sb.toString();}
    throw new Error("Missing return statement in function");
  }

/** Consumes and returns a "word", where a quote token is a word. */
  final public String wordq() throws ParseException {
                Token t;
    if (jj_2_45(3)) {
      t = jj_consume_token(WS);
    } else if (jj_2_46(3)) {
      t = jj_consume_token(WORD);
    } else if (jj_2_47(3)) {
      t = jj_consume_token(EQ);
    } else if (jj_2_48(3)) {
      t = jj_consume_token(LPAREN);
    } else if (jj_2_49(3)) {
      t = jj_consume_token(RPAREN);
    } else if (jj_2_50(3)) {
      t = jj_consume_token(AT);
    } else if (jj_2_51(3)) {
      t = jj_consume_token(QCHAR);
    } else if (jj_2_52(3)) {
      t = jj_consume_token(STR);
    } else if (jj_2_53(3)) {
      t = jj_consume_token(COMMA);
    } else if (jj_2_54(3)) {
      t = jj_consume_token(HASH);
    } else if (jj_2_55(3)) {
      t = jj_consume_token(PRE);
    } else if (jj_2_56(3)) {
      t = jj_consume_token(QUOTE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return(t.toString());}
    throw new Error("Missing return statement in function");
  }

/** Consumes and returns a "word", where a quote token is not a word. */
  final public String word() throws ParseException {
               Token t;
    if (jj_2_57(3)) {
      t = jj_consume_token(WS);
    } else if (jj_2_58(3)) {
      t = jj_consume_token(WORD);
    } else if (jj_2_59(3)) {
      t = jj_consume_token(EQ);
    } else if (jj_2_60(3)) {
      t = jj_consume_token(LPAREN);
    } else if (jj_2_61(3)) {
      t = jj_consume_token(RPAREN);
    } else if (jj_2_62(3)) {
      t = jj_consume_token(AT);
    } else if (jj_2_63(3)) {
      t = jj_consume_token(QCHAR);
    } else if (jj_2_64(3)) {
      t = jj_consume_token(STR);
    } else if (jj_2_65(3)) {
      t = jj_consume_token(COMMA);
    } else if (jj_2_66(3)) {
      t = jj_consume_token(HASH);
    } else if (jj_2_67(3)) {
      t = jj_consume_token(PRE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
         {if (true) return(t.toString());}
    throw new Error("Missing return statement in function");
  }

  final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  final private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  final private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  final private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  final private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  final private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  final private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  final private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  final private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  final private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  final private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  final private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  final private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  final private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  final private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  final private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  final private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  final private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  final private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  final private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  final private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  final private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  final private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  final private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  final private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  final private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  final private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  final private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  final private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  final private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  final private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  final private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  final private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  final private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_37(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(36, xla); }
  }

  final private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_38(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(37, xla); }
  }

  final private boolean jj_2_39(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_39(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(38, xla); }
  }

  final private boolean jj_2_40(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_40(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(39, xla); }
  }

  final private boolean jj_2_41(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_41(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(40, xla); }
  }

  final private boolean jj_2_42(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_42(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(41, xla); }
  }

  final private boolean jj_2_43(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_43(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(42, xla); }
  }

  final private boolean jj_2_44(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_44(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(43, xla); }
  }

  final private boolean jj_2_45(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_45(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(44, xla); }
  }

  final private boolean jj_2_46(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_46(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(45, xla); }
  }

  final private boolean jj_2_47(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_47(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(46, xla); }
  }

  final private boolean jj_2_48(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_48(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(47, xla); }
  }

  final private boolean jj_2_49(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_49(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(48, xla); }
  }

  final private boolean jj_2_50(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_50(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(49, xla); }
  }

  final private boolean jj_2_51(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_51(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(50, xla); }
  }

  final private boolean jj_2_52(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_52(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(51, xla); }
  }

  final private boolean jj_2_53(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_53(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(52, xla); }
  }

  final private boolean jj_2_54(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_54(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(53, xla); }
  }

  final private boolean jj_2_55(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_55(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(54, xla); }
  }

  final private boolean jj_2_56(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_56(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(55, xla); }
  }

  final private boolean jj_2_57(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_57(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(56, xla); }
  }

  final private boolean jj_2_58(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_58(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(57, xla); }
  }

  final private boolean jj_2_59(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_59(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(58, xla); }
  }

  final private boolean jj_2_60(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_60(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(59, xla); }
  }

  final private boolean jj_2_61(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_61(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(60, xla); }
  }

  final private boolean jj_2_62(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_62(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(61, xla); }
  }

  final private boolean jj_2_63(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_63(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(62, xla); }
  }

  final private boolean jj_2_64(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_64(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(63, xla); }
  }

  final private boolean jj_2_65(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_65(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(64, xla); }
  }

  final private boolean jj_2_66(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_66(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(65, xla); }
  }

  final private boolean jj_2_67(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_67(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(66, xla); }
  }

  final private boolean jj_3_54() {
    if (jj_scan_token(HASH)) return true;
    return false;
  }

  final private boolean jj_3_6() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  final private boolean jj_3_65() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  final private boolean jj_3_14() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3R_8() {
    if (jj_scan_token(AT)) return true;
    if (jj_scan_token(WORD)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_19()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) return true;
    }
    return false;
  }

  final private boolean jj_3_5() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_53() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  final private boolean jj_3_18() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  final private boolean jj_3_10() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_64() {
    if (jj_scan_token(STR)) return true;
    return false;
  }

  final private boolean jj_3_4() {
    if (jj_3R_9()) return true;
    return false;
  }

  final private boolean jj_3_7() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_17() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  final private boolean jj_3R_7() {
    if (jj_scan_token(AT)) return true;
    if (jj_scan_token(STR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) return true;
    }
    return false;
  }

  final private boolean jj_3_8() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_52() {
    if (jj_scan_token(STR)) return true;
    return false;
  }

  final private boolean jj_3_13() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_10()) jj_scanpos = xsp;
    if (jj_3R_10()) return true;
    xsp = jj_scanpos;
    if (jj_3_11()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_3() {
    if (jj_3R_8()) return true;
    return false;
  }

  final private boolean jj_3_63() {
    if (jj_scan_token(QCHAR)) return true;
    return false;
  }

  final private boolean jj_3_12() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) jj_scanpos = xsp;
    if (jj_3R_10()) return true;
    xsp = jj_scanpos;
    if (jj_3_9()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  final private boolean jj_3R_9() {
    if (jj_scan_token(AT)) return true;
    if (jj_scan_token(PRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) return true;
    }
    return false;
  }

  final private boolean jj_3_51() {
    if (jj_scan_token(QCHAR)) return true;
    return false;
  }

  final private boolean jj_3_2() {
    if (jj_3R_7()) return true;
    return false;
  }

  final private boolean jj_3_1() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3_62() {
    if (jj_scan_token(AT)) return true;
    return false;
  }

  final private boolean jj_3_50() {
    if (jj_scan_token(AT)) return true;
    return false;
  }

  final private boolean jj_3_61() {
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_49() {
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_60() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  final private boolean jj_3_48() {
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  final private boolean jj_3_59() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  final private boolean jj_3_47() {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  final private boolean jj_3_58() {
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  final private boolean jj_3_46() {
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  final private boolean jj_3_57() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_57()) {
    jj_scanpos = xsp;
    if (jj_3_58()) {
    jj_scanpos = xsp;
    if (jj_3_59()) {
    jj_scanpos = xsp;
    if (jj_3_60()) {
    jj_scanpos = xsp;
    if (jj_3_61()) {
    jj_scanpos = xsp;
    if (jj_3_62()) {
    jj_scanpos = xsp;
    if (jj_3_63()) {
    jj_scanpos = xsp;
    if (jj_3_64()) {
    jj_scanpos = xsp;
    if (jj_3_65()) {
    jj_scanpos = xsp;
    if (jj_3_66()) {
    jj_scanpos = xsp;
    if (jj_3_67()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3_45() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_45()) {
    jj_scanpos = xsp;
    if (jj_3_46()) {
    jj_scanpos = xsp;
    if (jj_3_47()) {
    jj_scanpos = xsp;
    if (jj_3_48()) {
    jj_scanpos = xsp;
    if (jj_3_49()) {
    jj_scanpos = xsp;
    if (jj_3_50()) {
    jj_scanpos = xsp;
    if (jj_3_51()) {
    jj_scanpos = xsp;
    if (jj_3_52()) {
    jj_scanpos = xsp;
    if (jj_3_53()) {
    jj_scanpos = xsp;
    if (jj_3_54()) {
    jj_scanpos = xsp;
    if (jj_3_55()) {
    jj_scanpos = xsp;
    if (jj_3_56()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  final private boolean jj_3_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_43()) {
    jj_scanpos = xsp;
    if (jj_3_44()) return true;
    }
    return false;
  }

  final private boolean jj_3_43() {
    if (jj_3R_16()) return true;
    return false;
  }

  final private boolean jj_3R_14() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_42()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3_44() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  final private boolean jj_3_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_40()) {
    jj_scanpos = xsp;
    if (jj_3_41()) return true;
    }
    return false;
  }

  final private boolean jj_3_40() {
    if (jj_3R_15()) return true;
    return false;
  }

  final private boolean jj_3R_13() {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3_41() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  final private boolean jj_3_27() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_35() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_38() {
    if (jj_scan_token(WORD)) return true;
    return false;
  }

  final private boolean jj_3_37() {
    if (jj_scan_token(QUOTE)) return true;
    if (jj_3R_14()) return true;
    if (jj_scan_token(QUOTE)) return true;
    return false;
  }

  final private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_36()) {
    jj_scanpos = xsp;
    if (jj_3_37()) {
    jj_scanpos = xsp;
    if (jj_3_38()) return true;
    }
    }
    return false;
  }

  final private boolean jj_3_36() {
    if (jj_scan_token(LBRACE)) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  final private boolean jj_3_26() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  final private boolean jj_3_23() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_34() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_34()) jj_scanpos = xsp;
    if (jj_scan_token(HASH)) return true;
    xsp = jj_scanpos;
    if (jj_3_35()) jj_scanpos = xsp;
    if (jj_3R_12()) return true;
    return false;
  }

  final private boolean jj_3_22() {
    if (jj_scan_token(COMMA)) return true;
    return false;
  }

  final private boolean jj_3R_10() {
    if (jj_3R_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  final private boolean jj_3_56() {
    if (jj_scan_token(QUOTE)) return true;
    return false;
  }

  final private boolean jj_3_24() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_67() {
    if (jj_scan_token(PRE)) return true;
    return false;
  }

  final private boolean jj_3_31() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_20() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_30() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_30()) jj_scanpos = xsp;
    if (jj_scan_token(WORD)) return true;
    xsp = jj_scanpos;
    if (jj_3_31()) jj_scanpos = xsp;
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  final private boolean jj_3_19() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_32() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_25() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  final private boolean jj_3_16() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_55() {
    if (jj_scan_token(PRE)) return true;
    return false;
  }

  final private boolean jj_3_11() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_29() {
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_24()) jj_scanpos = xsp;
    if (jj_scan_token(WORD)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_25()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3_26()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_27()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  final private boolean jj_3_15() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  final private boolean jj_3_66() {
    if (jj_scan_token(HASH)) return true;
    return false;
  }

  final private boolean jj_3_28() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_20()) jj_scanpos = xsp;
    if (jj_scan_token(WORD)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_21()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_3_22()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3_23()) jj_scanpos = xsp;
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  final private boolean jj_3_21() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  final private boolean jj_3_9() {
    if (jj_scan_token(WS)) return true;
    return false;
  }

  public BibtexGrammarTokenManager token_source;
  SimpleCharStream jj_input_stream;
  public Token token, jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  public boolean lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static {
      jj_la1_0();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[67];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  public BibtexGrammar(java.io.InputStream stream) {
     this(stream, null);
  }
  public BibtexGrammar(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new BibtexGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public BibtexGrammar(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new BibtexGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public BibtexGrammar(BibtexGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(BibtexGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.Vector jj_expentries = new java.util.Vector();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[16];
    for (int i = 0; i < 16; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 16; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  final public void enable_tracing() {
  }

  final public void disable_tracing() {
  }

  final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 67; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
            case 38: jj_3_39(); break;
            case 39: jj_3_40(); break;
            case 40: jj_3_41(); break;
            case 41: jj_3_42(); break;
            case 42: jj_3_43(); break;
            case 43: jj_3_44(); break;
            case 44: jj_3_45(); break;
            case 45: jj_3_46(); break;
            case 46: jj_3_47(); break;
            case 47: jj_3_48(); break;
            case 48: jj_3_49(); break;
            case 49: jj_3_50(); break;
            case 50: jj_3_51(); break;
            case 51: jj_3_52(); break;
            case 52: jj_3_53(); break;
            case 53: jj_3_54(); break;
            case 54: jj_3_55(); break;
            case 55: jj_3_56(); break;
            case 56: jj_3_57(); break;
            case 57: jj_3_58(); break;
            case 58: jj_3_59(); break;
            case 59: jj_3_60(); break;
            case 60: jj_3_61(); break;
            case 61: jj_3_62(); break;
            case 62: jj_3_63(); break;
            case 63: jj_3_64(); break;
            case 64: jj_3_65(); break;
            case 65: jj_3_66(); break;
            case 66: jj_3_67(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
